In [21]:
import numpy as np
##1##
a = np.linspace(1, 10, num=10)
print(f"A = {a}")

A = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [3]:
##2##
b = np.zeros((3, 3), dtype=int)
print(f"B = {b}")

B = [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
##3##
rng = np.random.default_rng()
a = rng.integers(10, size=(5, 5))
print(f"A = {a}")

A = [[7 8 5 3 6]
 [4 9 8 6 8]
 [5 0 2 2 2]
 [6 1 8 8 3]
 [6 2 9 5 2]]


In [5]:
##4##
b = np.random.random((4, 4))
print(f"B = {b}")

B = [[0.42311002 0.35580662 0.51931874 0.98537037]
 [0.90829919 0.83340147 0.53357643 0.4779764 ]
 [0.20149529 0.41743371 0.7945148  0.69403878]
 [0.83146216 0.90228447 0.12103204 0.29233021]]


In [6]:
##5##
rng = np.random.default_rng()
a = rng.integers(10, size=(5,))
b = rng.integers(10, size=(5,))
print(f"A = {a}")
print(f"B = {b}")
print(f"A+B = {a+b}")
print(f"A-B = {a-b}")
print(f"A*B = {a*b}")

A = [1 0 9 7 1]
B = [9 0 9 8 2]
A+B = [10  0 18 15  3]
A-B = [-8  0  0 -1 -1]
A*B = [ 9  0 81 56  2]


In [7]:
##6##
a = rng.integers(10, size=(7,))
b = rng.integers(10, size=(7,))
print(f"A = {a}")
print(f"B = {b}")
print(f"scalar(A*B) = {np.dot(a,b)}")

A = [0 2 8 5 0 6 6]
B = [0 9 3 2 2 3 5]
scalar(A*B) = 100


In [8]:
##7##
a = rng.integers(10, size=(2,2))
b = rng.integers(10, size=(2,3))
print(f"A = {a}")
print(f"B = {b}")
print(f"A*B = {np.dot(a,b)}")

A = [[3 3]
 [1 0]]
B = [[2 9 3]
 [2 3 4]]
A*B = [[12 36 21]
 [ 2  9  3]]


In [9]:
##8##
a = rng.integers(10, size=(3,3))
print(f"A = {a}")
a_inv = np.linalg.inv(a)
print(f"A_inv = {a_inv}")
print(f"scalar(A*A_inv) = {np.dot(a, a_inv)}")

A = [[5 7 5]
 [1 1 8]
 [5 4 0]]
A_inv = [[-0.27826087  0.17391304  0.44347826]
 [ 0.34782609 -0.2173913  -0.30434783]
 [-0.00869565  0.13043478 -0.0173913 ]]
scalar(A*A_inv) = [[ 1.00000000e+00 -2.77555756e-17 -1.31838984e-16]
 [-5.55111512e-17  1.00000000e+00 -5.55111512e-17]
 [-4.44089210e-16  0.00000000e+00  1.00000000e+00]]


In [10]:
##9##
a = np.random.random((4, 4))
print(f"A = {a}")
print(f"A.T = {a.T}")

A = [[0.35040325 0.96852625 0.68649386 0.5558446 ]
 [0.32635458 0.79015947 0.007963   0.66255103]
 [0.0834847  0.67978515 0.30956942 0.56223988]
 [0.50563625 0.7516458  0.29586401 0.62269763]]
A.T = [[0.35040325 0.32635458 0.0834847  0.50563625]
 [0.96852625 0.79015947 0.67978515 0.7516458 ]
 [0.68649386 0.007963   0.30956942 0.29586401]
 [0.5558446  0.66255103 0.56223988 0.62269763]]


In [11]:
##10##
a = rng.integers(10, size=(3,4))
b = rng.integers(10, size=(4,))
print(f"A = {a}")
print(f"B = {b}")
print(f"A*B = {a*b}")
print(f"scalar(a*b) = {np.dot(a,b)}")

A = [[0 3 4 6]
 [3 1 3 6]
 [2 4 2 4]]
B = [6 3 9 1]
A*B = [[ 0  9 36  6]
 [18  3 27  6]
 [12 12 18  4]]
scalar(a*b) = [51 54 46]


In [12]:
##11##
a = np.random.random((2, 3))
b = np.random.random((3,))
print(f"A = {a}")
print(f"B = {b}")
print(f"A*B = {a*b}")
print(f"scalar(A*B) = {np.dot(a,b)}")

A = [[0.28458895 0.06124685 0.18729649]
 [0.4120767  0.5401774  0.15745245]]
B = [0.64319738 0.57709467 0.22455136]
A*B = [[0.18304687 0.03534523 0.04205768]
 [0.26504665 0.3117335  0.03535616]]
scalar(A*B) = [0.26044978 0.61213631]


In [13]:
##12##
a = rng.integers(10, size=(2,2))
b = rng.integers(10, size=(2,2))
print(f"A = {a}")
print(f"B = {b}")
print(f"A*B = {a*b}")

A = [[3 6]
 [9 6]]
B = [[6 9]
 [0 7]]
A*B = [[18 54]
 [ 0 42]]


In [14]:
##13##
a = rng.integers(100, size=(2,2))
b = rng.integers(100, size=(2,2))
print(f"A = {a}")
print(f"B = {b}")
print(f"A*B = {a*b}")
print(f"scalar(A*B) = {np.dot(a,b)}")

A = [[ 4 86]
 [ 6 54]]
B = [[24 50]
 [18 59]]
A*B = [[  96 4300]
 [ 108 3186]]
scalar(A*B) = [[1644 5274]
 [1116 3486]]


In [15]:
##14##
a = rng.integers(100, size=(5,5))
print(f"A = {a}")
b=np.array(u"\u2211", dtype="U")
print(f"{b}A= {a.sum()}")

A = [[ 3 54 33 16 21]
 [67 18 30 92 49]
 [40 47  5 72 79]
 [ 7 51 28 73  1]
 [11 26 12 19 12]]
∑A= 866


In [16]:
##15##
a = rng.integers(10, size=(4,4))
b = rng.integers(10, size=(4,4))
print(f"A = {a}")
print(f"B = {b}")
print(f"A-B = {a-b}")

A = [[9 8 6 1]
 [5 7 2 3]
 [5 8 9 4]
 [1 6 0 1]]
B = [[4 2 3 8]
 [5 6 2 3]
 [0 2 8 2]
 [5 1 4 9]]
A-B = [[ 5  6  3 -7]
 [ 0  1  0  0]
 [ 5  6  1  2]
 [-4  5 -4 -8]]


In [17]:
##16##
a = np.random.random((3, 3))
b = np.random.random((3,))
print(f"A = {a}")
b = np.ones((3,), dtype=float)
print(b)
print(f"scalar(A*B) = {np.dot(a,b)}")

A = [[0.33357686 0.72750963 0.3176383 ]
 [0.13041321 0.7051841  0.49322254]
 [0.72616805 0.17777209 0.08186132]]
[1. 1. 1.]
scalar(A*B) = [1.3787248  1.32881985 0.98580146]


In [18]:
##17##
a = rng.integers(10, size=(3,4))
print(f"A = {a}")
print(f"A*A = {a*a}")

A = [[3 1 6 5]
 [1 8 9 8]
 [7 6 4 7]]
A*A = [[ 9  1 36 25]
 [ 1 64 81 64]
 [49 36 16 49]]


In [19]:
a = rng.integers(50, size=(4,))
print(f"A = {a}")
b =np.sqrt(a)
print(f"sqrt(A) = {b}")

A = [ 4 14 13 14]
sqrt(A) = [2.         3.74165739 3.60555128 3.74165739]
